version: "3.7"

services:
  spring-transfer:
    image: transfer-spring:latest
    ports:
    - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://spring-postgres-db:5432/spring
    networks:
      - database

networks:
  database:
    external:
      name: spring-database
