version: "3.7"

services:
  spring-postgres-db:
    restart: always
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: spring
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    networks:
      - database

networks:
  database:
    name: spring-database
