spring:
  datasource.url: jdbc:postgresql://localhost:5432/spring
  datasource:
    driver-class-name: org.postgresql.Driver
    username: spring
    password: spring
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.jdbc.lob.non_contextual_creation: true
