spring:
  datasource.url: jdbc:h2:mem:transfer
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
